# 데이터 전처리

# refined_data.csv 로 데이터 전처리 진행

In [43]:
import pandas as pan

df = pan.read_csv("refined_data.csv", encoding = "UTF-8")

In [44]:
df.drop('Unnamed: 0', axis = 1, inplace = True)
#df
total_df = df.sort_values(by=['cor_code'], axis=0)
#total_df

In [45]:
FEB_2 = total_df.iloc[:,0:15]
MAR_2 = total_df.iloc[:,15:29]
APR_2 = total_df.iloc[:,29:43]
MAY_2 = total_df.iloc[:,43:57]
JUN_2 = total_df.iloc[:,57:71]
JUL_2 = total_df.iloc[:,71:85]
AUG_2 = total_df.iloc[:,85:99]
SEP_2 = total_df.iloc[:,99:113]
OCT_2 = total_df.iloc[:,113:127]
NOV_2 = total_df.iloc[:,127:141]
DEC_2 = total_df.iloc[:,141:155]
Jan_2 = total_df.iloc[:,155:169] 

#FEB_2

#분기 값을 채울 수 있도록!
#fst = 18  1분기
fst ="1분기결측"
FEB_3=FEB_2.fillna(fst)
MAR_3=MAR_2.fillna(fst)
#sec = 28  2분기
sec ="2분기결측"
APR_3=APR_2.fillna(sec)
MAY_3=MAY_2.fillna(sec)
JUN_3=JUN_2.fillna(sec)
#trd = 38  3분기
trd ="3분기결측"
JUL_3=JUL_2.fillna(trd)
AUG_3=AUG_2.fillna(trd)
SEP_3=SEP_2.fillna(trd)
#qua = 48  4분기
qua ="4분기결측"
OCT_3=OCT_2.fillna(qua)
NOV_3=NOV_2.fillna(qua)
DEC_3=DEC_2.fillna(qua)
분기값은 보여주기 위한 시각화 자료임 NAN을 bfill 및 ffill로 처리 할것이기 위해 주석처리

In [46]:
FEB_3=FEB_2.rename(columns = {'X1_x':'지역','X2_x':'규모','X16_x' : '기업유형', 'X21_x': '경기전망', 'X33_x':'내수전망','X35_x':'수출전망','X36_x':'영업이익실적','X38_x':'자금사정실적','X57_x':'판매대금회수지연','X58_x':'자금조달곤란','X59_x':'업체간 과당경쟁','X60_x':'인력확보난','X61_x':'인건비상승','month_x':'월'})
MAR_3=MAR_2.rename(columns = {'X1_y':'지역','X2_y':'규모','X16_y' : '기업유형', 'X21_y': '경기전망', 'X33_y':'내수전망','X35_y':'수출전망','X36_y':'영업이익실적','X38_y':'자금사정실적','X57_y':'판매대금회수지연','X58_y':'자금조달곤란','X59_y':'업체간 과당경쟁','X60_y':'인력확보난','X61_y':'인건비상승','month_y':'월'})
APR_3=APR_2.rename(columns = {'X1_x.1':'지역','X2_x.1':'규모','X16_x.1' : '기업유형', 'X21_x.1': '경기전망', 'X33_x.1':'내수전망','X35_x.1':'수출전망','X36_x.1':'영업이익실적','X38_x.1':'자금사정실적','X57_x.1':'판매대금회수지연','X58_x.1':'자금조달곤란','X59_x.1':'업체간 과당경쟁','X60_x.1':'인력확보난','X61_x.1':'인건비상승','month_x.1':'월'})
MAY_3=MAY_2.rename(columns = {'X1_y.1':'지역','X2_y.1':'규모','X16_y.1' : '기업유형', 'X21_y.1': '경기전망', 'X33_y.1':'내수전망','X35_y.1':'수출전망','X36_y.1':'영업이익실적','X38_y.1':'자금사정실적','X57_y.1':'판매대금회수지연','X58_y.1':'자금조달곤란','X59_y.1':'업체간 과당경쟁','X60_y.1':'인력확보난','X61_y.1':'인건비상승','month_y.1':'월'})
JUN_3=JUN_2.rename(columns = {'X1_x.2':'지역','X2_x.2':'규모','X16_x.2' : '기업유형', 'X21_x.2': '경기전망', 'X33_x.2':'내수전망','X35_x.2':'수출전망','X36_x.2':'영업이익실적','X38_x.2':'자금사정실적','X57_x.2':'판매대금회수지연','X58_x.2':'자금조달곤란','X59_x.2':'업체간 과당경쟁','X60_x.2':'인력확보난','X61_x.2':'인건비상승','month_x.2':'월'})
JUL_3=JUL_2.rename(columns = {'X1_y.2':'지역','X2_y.2':'규모','X16_y.2' : '기업유형', 'X21_y.2': '경기전망', 'X33_y.2':'내수전망','X35_y.2':'수출전망','X36_y.2':'영업이익실적','X38_y.2':'자금사정실적','X57_y.2':'판매대금회수지연','X58_y.2':'자금조달곤란','X59_y.2':'업체간 과당경쟁','X60_y.2':'인력확보난','X61_y.2':'인건비상승','month_y.2':'월'})
AUG_3=AUG_2.rename(columns = {'X1_x.3':'지역','X2_x.3':'규모','X16_x.3' : '기업유형', 'X21_x.3': '경기전망', 'X33_x.3':'내수전망','X35_x.3':'수출전망','X36_x.3':'영업이익실적','X38_x.3':'자금사정실적','X57_x.3':'판매대금회수지연','X58_x.3':'자금조달곤란','X59_x.3':'업체간 과당경쟁','X60_x.3':'인력확보난','X61_x.3':'인건비상승','month_x.3':'월'})
SEP_3=SEP_2.rename(columns = {'X1_y.3':'지역','X2_y.3':'규모','X16_y.3' : '기업유형', 'X21_y.3': '경기전망', 'X33_y.3':'내수전망','X35_y.3':'수출전망','X36_y.3':'영업이익실적','X38_y.3':'자금사정실적','X57_y.3':'판매대금회수지연','X58_y.3':'자금조달곤란','X59_y.3':'업체간 과당경쟁','X60_y.3':'인력확보난','X61_y.3':'인건비상승','month_y.3':'월'})
OCT_3=OCT_2.rename(columns = {'X1_x.4':'지역','X2_x.4':'규모','X16_x.4' : '기업유형', 'X21_x.4': '경기전망', 'X33_x.4':'내수전망','X35_x.4':'수출전망','X36_x.4':'영업이익실적','X38_x.4':'자금사정실적','X57_x.4':'판매대금회수지연','X58_x.4':'자금조달곤란','X59_x.4':'업체간 과당경쟁','X60_x.4':'인력확보난','X61_x.4':'인건비상승','month_x.4':'월'})
NOV_3=NOV_2.rename(columns = {'X1_y.4':'지역','X2_y.4':'규모','X16_y.4' : '기업유형', 'X21_y.4': '경기전망', 'X33_y.4':'내수전망','X35_y.4':'수출전망','X36_y.4':'영업이익실적','X38_y.4':'자금사정실적','X57_y.4':'판매대금회수지연','X58_y.4':'자금조달곤란','X59_y.4':'업체간 과당경쟁','X60_y.4':'인력확보난','X61_y.4':'인건비상승','month_y.4':'월'})
DEC_3=DEC_2.rename(columns = {'X1_x.5':'지역','X2_x.5':'규모','X16_x.5' : '기업유형', 'X21_x.5': '경기전망', 'X33_x.5':'내수전망','X35_x.5':'수출전망','X36_x.5':'영업이익실적','X38_x.5':'자금사정실적','X57_x.5':'판매대금회수지연','X58_x.5':'자금조달곤란','X59_x.5':'업체간 과당경쟁','X60_x.5':'인력확보난','X61_x.5':'인건비상승','month_x.5':'월'})
Jan_3=Jan_2.rename(columns = {'X1_y.5':'지역','X2_y.5':'규모','X16_y.5' : '기업유형', 'X21_y.5': '경기전망', 'X33_y.5':'내수전망','X35_y.5':'수출전망','X36_y.5':'영업이익실적','X38_y.5':'자금사정실적','X57_y.5':'판매대금회수지연','X58_y.5':'자금조달곤란','X59_y.5':'업체간 과당경쟁','X60_y.5':'인력확보난','X61_y.5':'인건비상승','month_y.5':'월'})

In [47]:
AC8=FEB_3.loc[:,['cor_code']] # 기업코드만 추출
AC8

     cor_code
0      240001
1      240002
2      240003
3      240004
4      240005
..        ...
190    360066
191    360067
192    360068
193    360069
196    360070

[197 rows x 1 columns]

In [48]:
MAR_4=pan.concat([MAR_3,AC8], axis= 1)
APR_4=pan.concat([APR_3,AC8], axis= 1)
MAY_4=pan.concat([MAY_3,AC8], axis= 1)
JUN_4=pan.concat([JUN_3,AC8], axis= 1)
JUL_4=pan.concat([JUL_3,AC8], axis= 1)
AUG_4=pan.concat([AUG_3,AC8], axis= 1)
SEP_4=pan.concat([SEP_3,AC8], axis= 1)
OCT_4=pan.concat([OCT_3,AC8], axis= 1)
NOV_4=pan.concat([NOV_3,AC8], axis= 1)
DEC_4=pan.concat([DEC_3,AC8], axis= 1)
Jan_4=pan.concat([Jan_3,AC8], axis= 1)

In [49]:
Joiner=pan.concat([FEB_3,MAR_4,APR_4,MAY_4,JUN_4,JUL_4,AUG_4,SEP_4,OCT_4,NOV_4,DEC_4,Jan_4])
#Joiner.to_csv("중간.csv")

Joiner.isnull().sum()

C:\Users\kgh\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

cor_code     0
경기전망        67
규모          67
기업유형        67
내수전망        67
수출전망        67
업체간 과당경쟁    67
영업이익실적      67
월           67
인건비상승       67
인력확보난       67
자금사정실적      67
자금조달곤란      67
지역          48
판매대금회수지연    67
dtype: int64

In [50]:
grb=Joiner.groupby(Joiner["cor_code"])
grb.mean()

,경기전망,규모,기업유형,내수전망,수출전망,업체간 과당경쟁,영업이익실적,월,인건비상승,인력확보난,자금사정실적,자금조달곤란,지역,판매대금회수지연
cor_code,,,,,,,,,,,,,,
240001,2.800000,5.0,2.0,2.100000,2.300000,0.400000,1.700000,8.800000,0.800000,0.000000,2.300000,0.200000,24.0,0.200000
240002,3.200000,1.0,1.0,3.200000,2.000000,0.000000,2.900000,7.400000,0.700000,0.700000,2.900000,0.100000,24.0,0.400000
240003,1.333333,4.0,2.0,1.333333,0.083333,0.916667,1.000000,8.083333,1.000000,0.583333,1.250000,1.000000,24.0,0.916667
240004,2.666667,3.5,1.0,2.750000,0.000000,0.833333,2.916667,8.083333,0.166667,0.000000,3.000000,0.000000,24.0,0.083333
240005,3.000000,1.0,1.0,3.000000,0.000000,0.083333,2.833333,8.083333,0.333333,0.000000,2.833333,0.083333,24.0,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360066,1.300000,2.0,1.0,1.300000,0.000000,0.300000,1.200000,9.200000,0.400000,0.300000,1.200000,1.000000,36.0,0.500000
360067,2.400000,2.0,1.0,2.400000,0.000000,0.600000,2.300000,9.200000,0.500000,0.100000,2.000000,0.900000,36.0,0.600000
360068,2.100000,3.0,1.0,1.500000,0.000000,0.000000,1.200000,9.200000,0.800000,0.100000,1.100000,0.900000,36.0,0.100000
360069,1.600000,6.0,1.6,1.600000,1.600000,0.300000,1.000000,9.200000,1.000000,0.200000,1.000000,1.000000,36.0,0.000000
360070,3.200000,2.0,1.0,3.200000,0.000000,0.200000,3.000000,9.200000,0.800000,0.000000,3.100000,0.000000,36.0,0.000000

In [51]:
fill_mean_func = lambda g: g.fillna(g.mean())

grb1=Joiner.groupby('cor_code').apply(fill_mean_func)
grb2=grb1.round()
grb3=grb2.iloc[12,3:16]
#grb2.to_csv("그룹_평균_결측치제거.csv")

grb2.iloc[:,3:16]

              기업유형  내수전망  수출전망  업체간 과당경쟁  영업이익실적     월  인건비상승  인력확보난  자금사정실적  \
cor_code
240001   0     2.0   3.0   3.0       0.0     2.0   2.0    1.0    0.0     3.0
         0     2.0   2.0   2.0       0.0     2.0   9.0    1.0    0.0     2.0
         0     2.0   4.0   3.0       1.0     1.0   4.0    1.0    0.0     2.0
         0     2.0   4.0   3.0       1.0     1.0   5.0    1.0    0.0     2.0
         0     2.0   2.0   2.0       0.0     2.0   9.0    1.0    0.0     2.0
...            ...   ...   ...       ...     ...   ...    ...    ...     ...
360070   196   1.0   3.0   0.0       0.0     4.0   9.0    1.0    0.0     4.0
         196   1.0   3.0   0.0       0.0     3.0  10.0    1.0    0.0     3.0
         196   1.0   3.0   0.0       0.0     3.0  11.0    1.0    0.0     3.0
         196   1.0   3.0   0.0       0.0     2.0  12.0    0.0    0.0     3.0
         196   1.0   3.0   0.0       1.0     3.0  20.0    0.0    0.0     3.0

              자금조달곤란    지역  판매대금회수지연
cor_code
240001   0       0.0  24.0       0.0
         0       0.0  24.0       0.0
         0       0.0  24.0       0.0
         0       0.0  24.0       0.0
         0       0.0  24.0       0.0
...              ...   ...       ...
360070   196     0.0  36.0       0.0
         196     0.0  36.0       0.0
         196     0.0  36.0       0.0
         196     0.0  36.0       0.0
         196     0.0  36.0       0.0

[2364 rows x 12 columns]

In [52]:
Jan_4.set_index(["cor_code"], inplace= True)

Jan_4

,지역,규모,기업유형,경기전망,내수전망,수출전망,영업이익실적,자금사정실적,판매대금회수지연,자금조달곤란,업체간 과당경쟁,인력확보난,인건비상승,월
cor_code,,,,,,,,,,,,,,
240001,24.0,5.0,2.0,2.0,1.0,3.0,2.0,2.0,0.0,0.0,1.0,0.0,1.0,20.0
240002,24.0,1.0,1.0,3.0,3.0,0.0,4.0,3.0,0.0,0.0,0.0,1.0,1.0,20.0
240003,24.0,4.0,2.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,20.0
240004,24.0,2.0,1.0,2.0,2.0,0.0,3.0,3.0,0.0,0.0,1.0,0.0,0.0,20.0
240005,24.0,1.0,1.0,3.0,3.0,0.0,3.0,3.0,1.0,0.0,0.0,0.0,0.0,20.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360066,36.0,2.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,20.0
360067,36.0,2.0,1.0,2.0,2.0,0.0,2.0,2.0,1.0,1.0,0.0,0.0,0.0,20.0
360068,36.0,3.0,1.0,2.0,2.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,20.0
360069,36.0,6.0,1.0,2.0,2.0,2.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,20.0
360070,36.0,2.0,1.0,3.0,3.0,0.0,3.0,3.0,0.0,0.0,1.0,0.0,0.0,20.0

In [53]:
grb2[0:12]

            cor_code  경기전망   규모  기업유형  내수전망  수출전망  업체간 과당경쟁  영업이익실적     월  \
cor_code
240001   0    240001   3.0  5.0   2.0   3.0   3.0       0.0     2.0   2.0
         0    240001   3.0  5.0   2.0   2.0   2.0       0.0     2.0   9.0
         0    240001   4.0  5.0   2.0   4.0   3.0       1.0     1.0   4.0
         0    240001   4.0  5.0   2.0   4.0   3.0       1.0     1.0   5.0
         0    240001   3.0  5.0   2.0   2.0   2.0       0.0     2.0   9.0
         0    240001   2.0  5.0   2.0   2.0   3.0       1.0     2.0   7.0
         0    240001   2.0  5.0   2.0   1.0   2.0       0.0     2.0   8.0
         0    240001   2.0  5.0   2.0   1.0   1.0       0.0     2.0   9.0
         0    240001   3.0  5.0   2.0   1.0   1.0       0.0     1.0  10.0
         0    240001   3.0  5.0   2.0   1.0   1.0       0.0     1.0  11.0
         0    240001   3.0  5.0   2.0   3.0   3.0       0.0     3.0  12.0
         0    240001   2.0  5.0   2.0   1.0   3.0       1.0     2.0  20.0

            인건비상승  인력확보난  자금사정실적  자금조달곤란    지역  판매대금회수지연
cor_code
240001   0    1.0    0.0     3.0     0.0  24.0       0.0
         0    1.0    0.0     2.0     0.0  24.0       0.0
         0    1.0    0.0     2.0     0.0  24.0       0.0
         0    1.0    0.0     2.0     0.0  24.0       0.0
         0    1.0    0.0     2.0     0.0  24.0       0.0
         0    1.0    0.0     3.0     0.0  24.0       0.0
         0    0.0    0.0     2.0     0.0  24.0       0.0
         0    1.0    0.0     2.0     1.0  24.0       0.0
         0    1.0    0.0     2.0     0.0  24.0       1.0
         0    1.0    0.0     2.0     1.0  24.0       1.0
         0    0.0    0.0     3.0     0.0  24.0       0.0
         0    1.0    0.0     2.0     0.0  24.0       0.0

In [54]:
grb2=grb2.drop(columns=["월", "지역", "규모", "기업유형"])
grb2[0:12]

            cor_code  경기전망  내수전망  수출전망  업체간 과당경쟁  영업이익실적  인건비상승  인력확보난  \
cor_code
240001   0    240001   3.0   3.0   3.0       0.0     2.0    1.0    0.0
         0    240001   3.0   2.0   2.0       0.0     2.0    1.0    0.0
         0    240001   4.0   4.0   3.0       1.0     1.0    1.0    0.0
         0    240001   4.0   4.0   3.0       1.0     1.0    1.0    0.0
         0    240001   3.0   2.0   2.0       0.0     2.0    1.0    0.0
         0    240001   2.0   2.0   3.0       1.0     2.0    1.0    0.0
         0    240001   2.0   1.0   2.0       0.0     2.0    0.0    0.0
         0    240001   2.0   1.0   1.0       0.0     2.0    1.0    0.0
         0    240001   3.0   1.0   1.0       0.0     1.0    1.0    0.0
         0    240001   3.0   1.0   1.0       0.0     1.0    1.0    0.0
         0    240001   3.0   3.0   3.0       0.0     3.0    0.0    0.0
         0    240001   2.0   1.0   3.0       1.0     2.0    1.0    0.0

            자금사정실적  자금조달곤란  판매대금회수지연
cor_code
240001   0     3.0     0.0       0.0
         0     2.0     0.0       0.0
         0     2.0     0.0       0.0
         0     2.0     0.0       0.0
         0     2.0     0.0       0.0
         0     3.0     0.0       0.0
         0     2.0     0.0       0.0
         0     2.0     1.0       0.0
         0     2.0     0.0       1.0
         0     2.0     1.0       1.0
         0     3.0     0.0       0.0
         0     2.0     0.0       0.0

In [72]:
GJ1=grb2.loc[240001]

In [73]:
GJ2=grb2.loc[240002]

In [74]:
GJ3=grb2.loc[240003]

In [75]:
GJ4=grb2.loc[240004]

In [76]:
GJ5=grb2.loc[240005]

In [77]:
GJ6=grb2.loc[240006]

In [78]:
GJ7=grb2.loc[240007]

In [79]:
GJ8=grb2.loc[240008]

In [80]:
GJ9=grb2.loc[240009]

In [81]:
GJ10=grb2.loc[240010]

In [82]:
GJ11=grb2.loc[240011]

In [83]:
GJ12=grb2.loc[240012]

In [84]:
GJ13=grb2.loc[240013]

In [85]:
GJ14=grb2.loc[240014]

In [86]:
GJ15=grb2.loc[240015]

In [87]:
GJ16=grb2.loc[240016]

In [88]:
GJ17=grb2.loc[240017]

In [89]:
GJ18=grb2.loc[240018]

In [90]:
GJ19=grb2.loc[240019]

In [91]:
GJ20=grb2.loc[240020]

In [92]:
GJ21=grb2.loc[240021]

In [93]:
GJ22=grb2.loc[240022]

In [94]:
GJ23=grb2.loc[240023]

In [95]:
GJ24=grb2.loc[240024]

In [96]:
GJ25=grb2.loc[240025]

In [97]:
GJ26=grb2.loc[240026]

In [98]:
GJ27=grb2.loc[240027]

In [99]:
GJ28=grb2.loc[240028]

In [100]:
GJ29=grb2.loc[240029]

In [101]:
GJ30=grb2.loc[240030]

In [102]:
GJ31=grb2.loc[240031]

In [103]:
GJ32=grb2.loc[240032]

In [104]:
GJ33=grb2.loc[240033]

In [105]:
GJ34=grb2.loc[240034]

In [106]:
GJ35=grb2.loc[240035]

In [107]:
GJ36=grb2.loc[240036]

In [108]:
GJ30=grb2.loc[240037]

In [109]:
GJ38=grb2.loc[240038]

In [110]:
GJ39=grb2.loc[240039]

In [111]:
GJ40=grb2.loc[240040]

In [112]:
GJ41=grb2.loc[240041]

In [113]:
GJ42=grb2.loc[240042]

In [114]:
GJ43=grb2.loc[240043]

In [115]:
GJ44=grb2.loc[240044]

In [116]:
GJ45=grb2.loc[240045]

In [117]:
GJ46=grb2.loc[240046]

In [118]:
GJ47=grb2.loc[240047]

In [119]:
GJ48=grb2.loc[240048]

In [120]:
GJ49=grb2.loc[240049]

In [121]:
GJ50=grb2.loc[240050]

In [122]:
GJ51=grb2.loc[240051]

In [123]:
GJ52=grb2.loc[240052]

In [124]:
GJ53=grb2.loc[240053]

In [125]:
GJ54=grb2.loc[240054]

In [126]:
GJ55=grb2.loc[240055]

In [127]:
GJ56=grb2.loc[240056]

In [128]:
GJ57=grb2.loc[240057]

In [129]:
GJ58=grb2.loc[240058]

In [130]:
GJ59=grb2.loc[240059]

In [131]:
GJ60=grb2.loc[240060]

In [132]:
GJ61=grb2.loc[240061]

In [133]:
GJ62=grb2.loc[240062]

In [134]:
GJ63=grb2.loc[240063]

In [135]:
GJ64=grb2.loc[240064]

In [136]:
GJ65=grb2.loc[240065]

In [137]:
GJ66=grb2.loc[240066]

In [138]:
GJ67=grb2.loc[240067]

In [139]:
GJ68=grb2.loc[240068]

In [140]:
GJ69=grb2.loc[240069]

In [141]:
GJ70=grb2.loc[240070]

In [142]:
GJ71=grb2.loc[240071]

In [143]:
GJ72=grb2.loc[240072]

In [144]:
GJ73=grb2.loc[240073]

In [145]:
GJ74=grb2.loc[240074]

In [146]:
GJ75=grb2.loc[240075]

In [147]:
GJ76=grb2.loc[240076]

In [148]:
GJ77=grb2.loc[240077]

In [149]:
GJ78=grb2.loc[240078]

In [150]:
GJ79=grb2.loc[240079]

In [151]:
GJ80=grb2.loc[240080]

In [152]:
GJ81=grb2.loc[240081]

In [153]:
GJ82=grb2.loc[240082]

In [154]:
GJ83=grb2.loc[240083]

In [155]:
GJ84=grb2.loc[240084]

In [156]:
GJ85=grb2.loc[240085]

In [157]:
GJ86=grb2.loc[240086]

In [158]:
GJ87=grb2.loc[240087]

In [159]:
GJ88=grb2.loc[240088]

In [160]:
GJ89=grb2.loc[240089]

In [161]:
GJ90=grb2.loc[240090]

In [162]:
GJ91=grb2.loc[240091]

In [163]:
GJ92=grb2.loc[240092]

In [164]:
GJ93=grb2.loc[240093]

In [165]:
GJ94=grb2.loc[240094]

In [166]:
GJ95=grb2.loc[240095]

In [167]:
GJ96=grb2.loc[240096]

In [168]:
GJ97=grb2.loc[240097]

In [169]:
GJ98=grb2.loc[240098]

In [170]:
GJ99=grb2.loc[240099]

In [171]:
GJ100=grb2.loc[240100]

In [172]:
GJ101=grb2.loc[240101]

In [173]:
GJ102=grb2.loc[240102]

In [174]:
GJ103=grb2.loc[240103]

In [175]:
GJ104=grb2.loc[240104]
GJ105=grb2.loc[240105]
GJ106=grb2.loc[240106]
GJ107=grb2.loc[240107]
GJ108=grb2.loc[240108]
GJ109=grb2.loc[240109]
GJ110=grb2.loc[240110]
GJ111=grb2.loc[240111]
GJ112=grb2.loc[240112]
GJ113=grb2.loc[240113]
GJ114=grb2.loc[240114]
GJ115=grb2.loc[240115]
GJ116=grb2.loc[240116]
GJ117=grb2.loc[240117]
GJ118=grb2.loc[240118]
GJ119=grb2.loc[240119]
GJ120=grb2.loc[240120]
GJ121=grb2.loc[240121]
GJ122=grb2.loc[240122]
GJ123=grb2.loc[240123]
GJ124=grb2.loc[240124]
GJ125=grb2.loc[240125]
GJ126=grb2.loc[240126]
GJ127=grb2.loc[240127]

In [176]:
GJ105=grb2.loc[240105]
GJ106=grb2.loc[240106]
GJ107=grb2.loc[240107]
GJ108=grb2.loc[240108]
GJ109=grb2.loc[240109]
GJ110=grb2.loc[240110]
GJ111=grb2.loc[240111]
GJ112=grb2.loc[240112]
GJ113=grb2.loc[240113]
GJ114=grb2.loc[240114]
GJ115=grb2.loc[240115]
GJ116=grb2.loc[240116]
GJ117=grb2.loc[240117]
GJ118=grb2.loc[240118]
GJ119=grb2.loc[240119]
GJ120=grb2.loc[240120]
GJ121=grb2.loc[240121]
GJ122=grb2.loc[240122]
GJ123=grb2.loc[240123]
GJ124=grb2.loc[240124]
GJ125=grb2.loc[240125]
GJ126=grb2.loc[240126]
GJ127=grb2.loc[240127]

In [177]:
GJ106=grb2.loc[240106]
GJ107=grb2.loc[240107]
GJ108=grb2.loc[240108]
GJ109=grb2.loc[240109]
GJ110=grb2.loc[240110]
GJ111=grb2.loc[240111]
GJ112=grb2.loc[240112]
GJ113=grb2.loc[240113]
GJ114=grb2.loc[240114]
GJ115=grb2.loc[240115]
GJ116=grb2.loc[240116]
GJ117=grb2.loc[240117]
GJ118=grb2.loc[240118]
GJ119=grb2.loc[240119]
GJ120=grb2.loc[240120]
GJ121=grb2.loc[240121]
GJ122=grb2.loc[240122]
GJ123=grb2.loc[240123]
GJ124=grb2.loc[240124]
GJ125=grb2.loc[240125]
GJ126=grb2.loc[240126]
GJ127=grb2.loc[240127]

In [178]:
GJ107=grb2.loc[240107]
GJ108=grb2.loc[240108]
GJ109=grb2.loc[240109]
GJ110=grb2.loc[240110]
GJ111=grb2.loc[240111]
GJ112=grb2.loc[240112]
GJ113=grb2.loc[240113]
GJ114=grb2.loc[240114]
GJ115=grb2.loc[240115]
GJ116=grb2.loc[240116]
GJ117=grb2.loc[240117]
GJ118=grb2.loc[240118]
GJ119=grb2.loc[240119]
GJ120=grb2.loc[240120]
GJ121=grb2.loc[240121]
GJ122=grb2.loc[240122]
GJ123=grb2.loc[240123]
GJ124=grb2.loc[240124]
GJ125=grb2.loc[240125]
GJ126=grb2.loc[240126]
GJ127=grb2.loc[240127]

In [179]:
GJ108=grb2.loc[240108]
GJ109=grb2.loc[240109]
GJ110=grb2.loc[240110]
GJ111=grb2.loc[240111]
GJ112=grb2.loc[240112]
GJ113=grb2.loc[240113]
GJ114=grb2.loc[240114]
GJ115=grb2.loc[240115]
GJ116=grb2.loc[240116]
GJ117=grb2.loc[240117]
GJ118=grb2.loc[240118]
GJ119=grb2.loc[240119]
GJ120=grb2.loc[240120]
GJ121=grb2.loc[240121]
GJ122=grb2.loc[240122]
GJ123=grb2.loc[240123]
GJ124=grb2.loc[240124]
GJ125=grb2.loc[240125]
GJ126=grb2.loc[240126]
GJ127=grb2.loc[240127]

In [180]:
GJ109=grb2.loc[240109]
GJ110=grb2.loc[240110]
GJ111=grb2.loc[240111]
GJ112=grb2.loc[240112]
GJ113=grb2.loc[240113]
GJ114=grb2.loc[240114]
GJ115=grb2.loc[240115]
GJ116=grb2.loc[240116]
GJ117=grb2.loc[240117]
GJ118=grb2.loc[240118]
GJ119=grb2.loc[240119]
GJ120=grb2.loc[240120]
GJ121=grb2.loc[240121]
GJ122=grb2.loc[240122]
GJ123=grb2.loc[240123]
GJ124=grb2.loc[240124]
GJ125=grb2.loc[240125]
GJ126=grb2.loc[240126]
GJ127=grb2.loc[240127]

In [181]:
GJ110=grb2.loc[240110]
GJ111=grb2.loc[240111]
GJ112=grb2.loc[240112]
GJ113=grb2.loc[240113]
GJ114=grb2.loc[240114]
GJ115=grb2.loc[240115]
GJ116=grb2.loc[240116]
GJ117=grb2.loc[240117]
GJ118=grb2.loc[240118]
GJ119=grb2.loc[240119]
GJ120=grb2.loc[240120]
GJ121=grb2.loc[240121]
GJ122=grb2.loc[240122]
GJ123=grb2.loc[240123]
GJ124=grb2.loc[240124]
GJ125=grb2.loc[240125]
GJ126=grb2.loc[240126]
GJ127=grb2.loc[240127]

In [182]:
GJ111=grb2.loc[240111]
GJ112=grb2.loc[240112]
GJ113=grb2.loc[240113]
GJ114=grb2.loc[240114]
GJ115=grb2.loc[240115]
GJ116=grb2.loc[240116]
GJ117=grb2.loc[240117]
GJ118=grb2.loc[240118]
GJ119=grb2.loc[240119]
GJ120=grb2.loc[240120]
GJ121=grb2.loc[240121]
GJ122=grb2.loc[240122]
GJ123=grb2.loc[240123]
GJ124=grb2.loc[240124]
GJ125=grb2.loc[240125]
GJ126=grb2.loc[240126]
GJ127=grb2.loc[240127]

In [183]:
GJ112=grb2.loc[240112]
GJ113=grb2.loc[240113]
GJ114=grb2.loc[240114]
GJ115=grb2.loc[240115]
GJ116=grb2.loc[240116]
GJ117=grb2.loc[240117]
GJ118=grb2.loc[240118]
GJ119=grb2.loc[240119]
GJ120=grb2.loc[240120]
GJ121=grb2.loc[240121]
GJ122=grb2.loc[240122]
GJ123=grb2.loc[240123]
GJ124=grb2.loc[240124]
GJ125=grb2.loc[240125]
GJ126=grb2.loc[240126]
GJ127=grb2.loc[240127]

In [184]:
GJ113=grb2.loc[240113]
GJ114=grb2.loc[240114]
GJ115=grb2.loc[240115]
GJ116=grb2.loc[240116]
GJ117=grb2.loc[240117]
GJ118=grb2.loc[240118]
GJ119=grb2.loc[240119]
GJ120=grb2.loc[240120]
GJ121=grb2.loc[240121]
GJ122=grb2.loc[240122]
GJ123=grb2.loc[240123]
GJ124=grb2.loc[240124]
GJ125=grb2.loc[240125]
GJ126=grb2.loc[240126]
GJ127=grb2.loc[240127]

In [185]:
GJ114=grb2.loc[240114]
GJ115=grb2.loc[240115]
GJ116=grb2.loc[240116]
GJ117=grb2.loc[240117]
GJ118=grb2.loc[240118]
GJ119=grb2.loc[240119]
GJ120=grb2.loc[240120]
GJ121=grb2.loc[240121]
GJ122=grb2.loc[240122]
GJ123=grb2.loc[240123]
GJ124=grb2.loc[240124]
GJ125=grb2.loc[240125]
GJ126=grb2.loc[240126]
GJ127=grb2.loc[240127]

In [186]:
GJ115=grb2.loc[240115]
GJ116=grb2.loc[240116]
GJ117=grb2.loc[240117]
GJ118=grb2.loc[240118]
GJ119=grb2.loc[240119]
GJ120=grb2.loc[240120]
GJ121=grb2.loc[240121]
GJ122=grb2.loc[240122]
GJ123=grb2.loc[240123]
GJ124=grb2.loc[240124]
GJ125=grb2.loc[240125]
GJ126=grb2.loc[240126]
GJ127=grb2.loc[240127]

In [187]:
GJ116=grb2.loc[240116]
GJ117=grb2.loc[240117]
GJ118=grb2.loc[240118]
GJ119=grb2.loc[240119]
GJ120=grb2.loc[240120]
GJ121=grb2.loc[240121]
GJ122=grb2.loc[240122]
GJ123=grb2.loc[240123]
GJ124=grb2.loc[240124]
GJ125=grb2.loc[240125]
GJ126=grb2.loc[240126]
GJ127=grb2.loc[240127]

In [188]:
GJ117=grb2.loc[240117]
GJ118=grb2.loc[240118]
GJ119=grb2.loc[240119]
GJ120=grb2.loc[240120]
GJ121=grb2.loc[240121]
GJ122=grb2.loc[240122]
GJ123=grb2.loc[240123]
GJ124=grb2.loc[240124]
GJ125=grb2.loc[240125]
GJ126=grb2.loc[240126]
GJ127=grb2.loc[240127]

In [189]:
GJ118=grb2.loc[240118]
GJ119=grb2.loc[240119]
GJ120=grb2.loc[240120]
GJ121=grb2.loc[240121]
GJ122=grb2.loc[240122]
GJ123=grb2.loc[240123]
GJ124=grb2.loc[240124]
GJ125=grb2.loc[240125]
GJ126=grb2.loc[240126]
GJ127=grb2.loc[240127]

In [190]:
GJ119=grb2.loc[240119]
GJ120=grb2.loc[240120]
GJ121=grb2.loc[240121]
GJ122=grb2.loc[240122]
GJ123=grb2.loc[240123]
GJ124=grb2.loc[240124]
GJ125=grb2.loc[240125]
GJ126=grb2.loc[240126]
GJ127=grb2.loc[240127]

In [191]:
GJ120=grb2.loc[240120]
GJ121=grb2.loc[240121]
GJ122=grb2.loc[240122]
GJ123=grb2.loc[240123]
GJ124=grb2.loc[240124]
GJ125=grb2.loc[240125]
GJ126=grb2.loc[240126]
GJ127=grb2.loc[240127]

In [192]:
GJ121=grb2.loc[240121]
GJ122=grb2.loc[240122]
GJ123=grb2.loc[240123]
GJ124=grb2.loc[240124]
GJ125=grb2.loc[240125]
GJ126=grb2.loc[240126]
GJ127=grb2.loc[240127]

In [193]:
GJ122=grb2.loc[240122]
GJ123=grb2.loc[240123]
GJ124=grb2.loc[240124]
GJ125=grb2.loc[240125]
GJ126=grb2.loc[240126]
GJ127=grb2.loc[240127]

In [194]:
GJ123=grb2.loc[240123]
GJ124=grb2.loc[240124]
GJ125=grb2.loc[240125]
GJ126=grb2.loc[240126]
GJ127=grb2.loc[240127]

In [195]:
GJ124=grb2.loc[240124]
GJ125=grb2.loc[240125]
GJ126=grb2.loc[240126]
GJ127=grb2.loc[240127]

In [196]:
GJ125=grb2.loc[240125]
GJ126=grb2.loc[240126]
GJ127=grb2.loc[240127]

In [197]:
GJ126=grb2.loc[240126]
GJ127=grb2.loc[240127]

In [198]:
GJ127=grb2.loc[240127]

In [199]:
GJ126

#JN1

,cor_code,경기전망,내수전망,수출전망,업체간 과당경쟁,영업이익실적,인건비상승,인력확보난,자금사정실적,자금조달곤란,판매대금회수지연
194,240126,2.0,2.0,0.0,0.0,2.0,1.0,0.0,2.0,1.0,0.0
194,240126,2.0,2.0,0.0,0.0,2.0,1.0,0.0,2.0,1.0,0.0
194,240126,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0
194,240126,2.0,2.0,0.0,0.0,2.0,1.0,0.0,2.0,1.0,0.0
194,240126,2.0,2.0,0.0,0.0,2.0,1.0,0.0,2.0,1.0,0.0
194,240126,2.0,2.0,0.0,0.0,2.0,1.0,0.0,2.0,1.0,0.0
194,240126,2.0,2.0,0.0,0.0,2.0,1.0,0.0,1.0,1.0,0.0
194,240126,2.0,2.0,0.0,0.0,2.0,1.0,0.0,1.0,1.0,0.0
194,240126,3.0,2.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0
194,240126,2.0,2.0,0.0,0.0,1.0,1.0,0.0,2.0,1.0,1.0
194,240126,3.0,3.0,0.0,0.0,2.0,0.0,0.0,2.0,1.0,1.0
194,240126,2.0,2.0,0.0,0.0,2.0,1.0,0.0,2.0,1.0,0.0

In [262]:
### 전남 기업에 대한 데이터프레임
### 해당 데이터프레임으로 위험도 산출 및 예측

#grb2 = grb2.drop(columns = ['기업유형','규모','월','지역'])
a = 360000

JN1 = grb2.loc[a+1]
JN2 = grb2.loc[a+2]
JN3 = grb2.loc[a+3]
JN4 = grb2.loc[a+4]
JN5 = grb2.loc[a+5]
JN6 = grb2.loc[a+6]
JN7 = grb2.loc[a+7]
JN8 = grb2.loc[a+8]
JN9 = grb2.loc[a+9]
JN10 = grb2.loc[a+10]
JN11 = grb2.loc[a+11]
JN12 = grb2.loc[a+12]
JN13 = grb2.loc[a+13]
JN14 = grb2.loc[a+14]
JN15 = grb2.loc[a+15]
JN16 = grb2.loc[a+16]
JN17 = grb2.loc[a+17]
JN18 = grb2.loc[a+18]
JN19 = grb2.loc[a+19]
JN20 = grb2.loc[a+20]
JN21 = grb2.loc[a+21]
JN22 = grb2.loc[a+22]
JN23 = grb2.loc[a+23]
JN24 = grb2.loc[a+24]
JN25 = grb2.loc[a+25]
JN26 = grb2.loc[a+26]
JN27 = grb2.loc[a+27]
JN28 = grb2.loc[a+28]
JN29 = grb2.loc[a+29]
JN30 = grb2.loc[a+30]
JN31 = grb2.loc[a+31]
JN32 = grb2.loc[a+32]
JN33 = grb2.loc[a+33]
JN34 = grb2.loc[a+34]
JN35 = grb2.loc[a+35]
JN36 = grb2.loc[a+36]
JN37 = grb2.loc[a+37]
JN38 = grb2.loc[a+38]
JN39 = grb2.loc[a+39]
JN40 = grb2.loc[a+40]
JN41 = grb2.loc[a+41]
JN42 = grb2.loc[a+42]
JN43 = grb2.loc[a+43]
JN44 = grb2.loc[a+44]
JN45 = grb2.loc[a+45]
JN46 = grb2.loc[a+46]
JN47 = grb2.loc[a+47]
JN48 = grb2.loc[a+48]
JN49 = grb2.loc[a+49]
JN50 = grb2.loc[a+50]
JN51 = grb2.loc[a+51]
JN52 = grb2.loc[a+52]
JN53 = grb2.loc[a+53]
JN54 = grb2.loc[a+54]
JN55 = grb2.loc[a+55]
JN56 = grb2.loc[a+56]
JN57 = grb2.loc[a+57]
JN58 = grb2.loc[a+58]
JN59 = grb2.loc[a+59]
JN60 = grb2.loc[a+60]
JN61 = grb2.loc[a+61]
JN62 = grb2.loc[a+62]
JN63 = grb2.loc[a+63]
JN64 = grb2.loc[a+64]
JN65 = grb2.loc[a+65]
JN66 = grb2.loc[a+66]
JN67 = grb2.loc[a+67]
JN68 = grb2.loc[a+68]
JN69 = grb2.loc[a+69]
JN70 = grb2.loc[a+70]

In [263]:
### 광주 기업에 대한 데이터프레임
### 해당 데이터프레임으로 위험도 산출 및 예측

b = 240000

GJ1 = grb2.loc[b+1]
GJ2 = grb2.loc[b+2]
GJ3 = grb2.loc[b+3]
GJ4 = grb2.loc[b+4]
GJ5 = grb2.loc[b+5]
GJ6 = grb2.loc[b+6]
GJ7 = grb2.loc[b+7]
GJ8 = grb2.loc[b+8]
GJ9 = grb2.loc[b+9]
GJ10 = grb2.loc[b+10]
GJ11 = grb2.loc[b+11]
GJ12 = grb2.loc[b+12]
GJ13 = grb2.loc[b+13]
GJ14 = grb2.loc[b+14]
GJ15 = grb2.loc[b+15]
GJ16 = grb2.loc[b+16]
GJ17 = grb2.loc[b+17]
GJ18 = grb2.loc[b+18]
GJ19 = grb2.loc[b+19]
GJ20 = grb2.loc[b+20]
GJ21 = grb2.loc[b+21]
GJ22 = grb2.loc[b+22]
GJ23 = grb2.loc[b+23]
GJ24 = grb2.loc[b+24]
GJ25 = grb2.loc[b+25]
GJ26 = grb2.loc[b+26]
GJ27 = grb2.loc[b+27]
GJ28 = grb2.loc[b+28]
GJ29 = grb2.loc[b+29]
GJ30 = grb2.loc[b+30]
GJ31 = grb2.loc[b+31]
GJ32 = grb2.loc[b+32]
GJ33 = grb2.loc[b+33]
GJ34 = grb2.loc[b+34]
GJ35 = grb2.loc[b+35]
GJ36 = grb2.loc[b+36]
GJ37 = grb2.loc[b+37]
GJ38 = grb2.loc[b+38]
GJ39 = grb2.loc[b+39]
GJ40 = grb2.loc[b+40]
GJ41 = grb2.loc[b+41]
GJ42 = grb2.loc[b+42]
GJ43 = grb2.loc[b+43]
GJ44 = grb2.loc[b+44]
GJ45 = grb2.loc[b+45]
GJ46 = grb2.loc[b+46]
GJ47 = grb2.loc[b+47]
GJ48 = grb2.loc[b+48]
GJ49 = grb2.loc[b+49]
GJ50 = grb2.loc[b+50]
GJ51 = grb2.loc[b+51]
GJ52 = grb2.loc[b+52]
GJ53 = grb2.loc[b+53]
GJ54 = grb2.loc[b+54]
GJ55 = grb2.loc[b+55]
GJ56 = grb2.loc[b+56]
GJ57 = grb2.loc[b+57]
GJ58 = grb2.loc[b+58]
GJ59 = grb2.loc[b+59]
GJ60 = grb2.loc[b+60]
GJ61 = grb2.loc[b+61]
GJ62 = grb2.loc[b+62]
GJ63 = grb2.loc[b+63]
GJ64 = grb2.loc[b+64]
GJ65 = grb2.loc[b+65]
GJ66 = grb2.loc[b+66]
GJ67 = grb2.loc[b+67]
GJ68 = grb2.loc[b+68]
GJ69 = grb2.loc[b+69]
GJ70 = grb2.loc[b+70]
GJ71 = grb2.loc[b+71]
GJ72 = grb2.loc[b+72]
GJ73 = grb2.loc[b+73]
GJ74 = grb2.loc[b+74]
GJ75 = grb2.loc[b+75]
GJ76 = grb2.loc[b+76]
GJ77 = grb2.loc[b+77]
GJ78 = grb2.loc[b+78]
GJ79 = grb2.loc[b+79]
GJ80 = grb2.loc[b+80]
GJ81 = grb2.loc[b+81]
GJ82 = grb2.loc[b+82]
GJ83 = grb2.loc[b+83]
GJ84 = grb2.loc[b+84]
GJ85 = grb2.loc[b+85]
GJ86 = grb2.loc[b+86]
GJ87 = grb2.loc[b+87]
GJ88 = grb2.loc[b+88]
GJ89 = grb2.loc[b+89]
GJ90 = grb2.loc[b+90]
GJ91 = grb2.loc[b+91]
GJ92 = grb2.loc[b+92]
GJ93 = grb2.loc[b+93]
GJ94 = grb2.loc[b+94]
GJ95 = grb2.loc[b+95]
GJ96 = grb2.loc[b+96]
GJ97 = grb2.loc[b+97]
GJ98 = grb2.loc[b+98]
GJ99 = grb2.loc[b+99]
GJ100 = grb2.loc[b+100]
GJ101 = grb2.loc[b+101]
GJ102 = grb2.loc[b+102]
GJ103 = grb2.loc[b+103]
GJ104 = grb2.loc[b+104]
GJ105 = grb2.loc[b+105]
GJ106 = grb2.loc[b+106]
GJ107 = grb2.loc[b+107]
GJ108 = grb2.loc[b+108]
GJ109 = grb2.loc[b+109]
GJ110 = grb2.loc[b+110]
GJ111 = grb2.loc[b+111]
GJ112 = grb2.loc[b+112]
GJ113 = grb2.loc[b+113]
GJ114 = grb2.loc[b+114]
GJ115 = grb2.loc[b+115]
GJ116 = grb2.loc[b+116]
GJ117 = grb2.loc[b+117]
GJ118 = grb2.loc[b+118]
GJ119 = grb2.loc[b+119]
GJ120 = grb2.loc[b+120]
GJ121 = grb2.loc[b+121]
GJ122 = grb2.loc[b+122]
GJ123 = grb2.loc[b+123]
GJ124 = grb2.loc[b+124]
GJ125 = grb2.loc[b+125]
GJ126 = grb2.loc[b+126]
GJ127 = grb2.loc[b+127]

In [265]:
# 자금사정실적(25), 내수전망(15), 판매대금회수지연(11), 자금조달곤란(9), 영업이익실적(8.5)
# 업체간과당경쟁(7.5), 경기전망(7), 인력확보난(6.5), 인건비상승(6), 수출전망(3.5)

# 자금사정실적 1~5(매우악화 ~ 매우호전), 내수전망 1~5(매우감소 ~ 매우증가), 판매대금회수지연 0, 1(미선택, 선택)
# 자금조달곤란 0, 1(미선택, 선택), 영업이익실적 1~5(매우감소 ~ 매우증가)
# 업체간과당경쟁 0, 1(미선택, 선택), 경기전망 1~5(매우나쁨 ~ 매우좋음), 인력확보난 0, 1(미선택, 선택)
# 인건비상승 0, 1(미선택, 선택), 수출전망 1~5(매우감소 ~ 매우증가)

# 경기전망 내수전망 수출전망 업체간 과당경쟁 영업이익실적 인건비상승 인력확보난 자금사정실적 자금조달곤란 판매대금회수지연
# 자금사정실적, 내수전망, 영업이익실적, 경기전망, 수출전망 5에 가까울수록 최대 퍼센테이지 : 
# 판매대금회수지연, 지금조달곤란, 업체간과당경쟁, 인력확보난, 인건비상승은 1이 최대 퍼센테이지, 0이면 없도록


feature = {0:'경기전망', 1:'내수전망', 2:'수출전망', 3:'영업이익실적', 4:'자금사정실적'} # 1부터 5까지 5구간으로 나뉘는 특징값

JNlist = [JN1, JN2, JN3, JN4, JN5, JN6, JN7, JN8, JN9, JN10, JN11, JN12, JN13, JN14, JN15, JN16, JN17, JN18, JN19, JN20, JN21, JN22, JN23,
         JN24, JN25, JN26, JN27, JN28, JN29, JN30, JN31, JN32, JN33, JN34, JN35, JN36, JN37, JN38, JN39, JN40, JN41, JN42, JN43, JN44,
         JN45, JN46, JN47, JN48, JN49, JN50, JN51, JN52, JN53, JN54, JN55, JN56, JN57, JN58, JN59, JN60, JN61, JN62, JN63, JN64, JN65,
         JN66, JN67, JN68, JN69, JN70]

for i in JNlist : # 1부터 70까지
    for k in feature.values() :

        i.loc[i[k] == 1, k] = 10
        i.loc[i[k] == 2, k] = 9
        i.loc[i[k] == 3, k] = 8
        i.loc[i[k] == 4, k] = 7
        i.loc[i[k] == 5, k] = 6

        i.loc[i[k] == 6, k] = 1
        i.loc[i[k] == 7, k] = 2
        i.loc[i[k] == 8, k] = 3
        i.loc[i[k] == 9, k] = 4
        i.loc[i[k] == 10, k] = 5
        
        i.reset_index(drop = True, inplace = True)
JN70

,cor_code,경기전망,내수전망,수출전망,업체간 과당경쟁,영업이익실적,인건비상승,인력확보난,자금사정실적,자금조달곤란,판매대금회수지연
0,360070,3.0,3.0,0.0,0.0,3.0,1.0,0.0,3.0,0.0,0.0
1,360070,3.0,3.0,0.0,0.0,3.0,1.0,0.0,3.0,0.0,0.0
2,360070,3.0,3.0,0.0,0.0,3.0,1.0,0.0,3.0,0.0,0.0
3,360070,3.0,3.0,0.0,0.0,3.0,1.0,0.0,3.0,0.0,0.0
4,360070,4.0,4.0,0.0,0.0,3.0,1.0,0.0,3.0,0.0,0.0
5,360070,3.0,3.0,0.0,1.0,3.0,1.0,0.0,3.0,0.0,0.0
6,360070,4.0,4.0,0.0,0.0,3.0,1.0,0.0,3.0,0.0,0.0
7,360070,3.0,3.0,0.0,0.0,4.0,1.0,0.0,4.0,0.0,0.0
8,360070,3.0,3.0,0.0,0.0,3.0,1.0,0.0,3.0,0.0,0.0
9,360070,3.0,3.0,0.0,0.0,3.0,1.0,0.0,3.0,0.0,0.0
10,360070,3.0,3.0,0.0,0.0,2.0,0.0,0.0,3.0,0.0,0.0
11,360070,3.0,3.0,0.0,1.0,3.0,0.0,0.0,3.0,0.0,0.0

In [266]:
GJlist = [GJ1, GJ2, GJ3, GJ4, GJ5, GJ6, GJ7, GJ8, GJ9, GJ10, GJ11, GJ12, GJ13, GJ14, GJ15, GJ16, GJ17, GJ18, GJ19, GJ20, GJ21, GJ22,
         GJ23, GJ24, GJ25, GJ26, GJ27, GJ28, GJ29, GJ30, GJ31, GJ32, GJ33, GJ34, GJ35, GJ36, GJ37, GJ38, GJ39, GJ40, GJ41, GJ42, GJ43,
         GJ44, GJ45, GJ46, GJ47, GJ48, GJ49, GJ50, GJ51, GJ52, GJ53, GJ54, GJ55, GJ56, GJ57, GJ58, GJ59, GJ60, GJ61, GJ62, GJ63, GJ64,
         GJ65, GJ66, GJ67, GJ68, GJ69, GJ70, GJ71, GJ72, GJ73, GJ74, GJ75, GJ76, GJ77, GJ78, GJ79, GJ80, GJ81, GJ82, GJ83, GJ84, GJ85,
         GJ86, GJ87, GJ88, GJ89, GJ90, GJ91, GJ92, GJ93, GJ94, GJ95, GJ96, GJ97, GJ98, GJ99, GJ100, GJ101, GJ102, GJ103, GJ104, GJ105,
         GJ106, GJ107, GJ108, GJ109, GJ110, GJ111, GJ112, GJ113, GJ114, GJ115, GJ116, GJ117, GJ118, GJ119, GJ120, GJ121, GJ122, GJ123,
         GJ124, GJ125, GJ126, GJ127]

for i in GJlist : # 1부터 127까지
    for k in feature.values() :

        i.loc[i[k] == 1, k] = 10
        i.loc[i[k] == 2, k] = 9
        i.loc[i[k] == 3, k] = 8
        i.loc[i[k] == 4, k] = 7
        i.loc[i[k] == 5, k] = 6

        i.loc[i[k] == 6, k] = 1
        i.loc[i[k] == 7, k] = 2
        i.loc[i[k] == 8, k] = 3
        i.loc[i[k] == 9, k] = 4
        i.loc[i[k] == 10, k] = 5
        
        i.reset_index(drop = True, inplace = True)
GJ127

,cor_code,경기전망,내수전망,수출전망,업체간 과당경쟁,영업이익실적,인건비상승,인력확보난,자금사정실적,자금조달곤란,판매대금회수지연
0,240127,3.0,3.0,3.0,0.0,3.0,1.0,0.0,3.0,0.0,0.0
1,240127,3.0,3.0,3.0,0.0,3.0,1.0,0.0,3.0,0.0,0.0
2,240127,4.0,4.0,4.0,0.0,3.0,1.0,0.0,3.0,0.0,0.0
3,240127,3.0,3.0,3.0,0.0,3.0,1.0,0.0,3.0,0.0,0.0
4,240127,3.0,3.0,3.0,0.0,3.0,1.0,0.0,3.0,0.0,0.0
5,240127,3.0,3.0,3.0,0.0,3.0,1.0,0.0,3.0,0.0,0.0
6,240127,3.0,3.0,3.0,0.0,3.0,1.0,0.0,3.0,0.0,0.0
7,240127,3.0,3.0,3.0,0.0,3.0,1.0,0.0,3.0,0.0,1.0
8,240127,3.0,3.0,3.0,0.0,3.0,1.0,0.0,3.0,0.0,0.0
9,240127,3.0,3.0,3.0,0.0,3.0,1.0,0.0,3.0,0.0,0.0
10,240127,3.0,3.0,4.0,0.0,3.0,0.0,0.0,3.0,0.0,1.0
11,240127,3.0,3.0,0.0,0.0,3.0,0.0,0.0,3.0,0.0,0.0

In [267]:
## 도산가능성 계산부분

for i in JNlist :
    i['도산가능성'] = 0.0 # 도산가능성 생성 후 초기화

# 계산하여 집어넣기
for i in JNlist :
    for k in range(0,12) :
        i['도산가능성'][k] = round((i['경기전망'][k]*1.4 + i['내수전망'][k]*3 + i['수출전망'][k]*0.7 + i['업체간 과당경쟁'][k]*7.5 + i['영업이익실적'][k]*1.7 + i['인건비상승'][k]*6 + i['인력확보난'][k]*6.5 + i['자금사정실적'][k]*5 + i['자금조달곤란'][k]*9 + i['판매대금회수지연'][k]*11) / 12, 2)
        
for i in GJlist :
    i['도산가능성'] = 0.0 # 도산가능성 생성 후 초기화

# 계산하여 집어넣기
for i in GJlist :
    for k in range(0,12) :
        i['도산가능성'][k] = round((i['경기전망'][k]*1.4 + i['내수전망'][k]*3 + i['수출전망'][k]*0.7 + i['업체간 과당경쟁'][k]*7.5 + i['영업이익실적'][k]*1.7 + i['인건비상승'][k]*6 + i['인력확보난'][k]*6.5 + i['자금사정실적'][k]*5 + i['자금조달곤란'][k]*9 + i['판매대금회수지연'][k]*11) / 12, 2)

#GJ115

C:\Users\kgh\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\kgh\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
C:\Users\kgh\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
C:\Users\kgh\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [268]:
# date 값 추가 및 인덱스화
date = ['2019-02-01', '2019-03-01', '2019-04-01', '2019-05-01', '2019-06-01', '2019-07-01', '2019-08-01', '2019-09-01',
        '2019-10-01', '2019-11-01', '2019-12-01', '2020-01-01']

## test code ##
#JN1['date'] = date
#JN1.set_index(JN1['date'], inplace = True, drop = True) # 인덱싱
#JN1.drop(JN1.columns[12], axis = 1, inplace = True) # date 열 삭제
## test code end ##


for i in JNlist :
    i['date'] = date
    i.set_index(i['date'], inplace = True, drop = True) # 인덱싱
    i.drop(i.columns[12], axis = 1, inplace = True) # date 열 삭제
    
for i in GJlist :
    i['date'] = date
    i.set_index(i['date'], inplace = True, drop = True) # 인덱싱
    i.drop(i.columns[12], axis = 1, inplace = True) # date 열 삭제

C:\Users\kgh\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\kgh\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [270]:
GJnum = 1
JNnum = 1

for i in GJlist :
    i.to_csv("./기업별데이터/광주/GJ"+str(GJnum)+".csv")
    GJnum += 1

for i in JNlist :
    i.to_csv("./기업별데이터/전남/JN"+str(JNnum)+".csv")
    JNnum += 1
    
#GJnum
#JNnum